# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YourAdsPoC3.0' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YourAdsPoC3.0

pod 'YourAdsSDK', :path => '../YourAdsSDK' 
pod 'Alamofire'

  target 'YourAdsPoC3.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YourAdsPoC3.0UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
