# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PoC 2.0' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PoC 2.0

pod 'YourAdsSDK', :path => '../YourAdsSDK/'
pod 'OpenCV'

  target 'PoC 2.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PoC 2.0UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
